development:
- cmd: npx ganache
  cmd_settings:
    accounts: 10
    evm_version: istanbul
    gas_limit: 12000000
    mnemonic: brownie
    port: 8545
  host: http://127.0.0.1
  id: development
  name: Ganache7
- cmd: npx hardhat node
  cmd_settings:
    port: 8545
  host: http://127.0.0.1
  id: hardhat
  name: Hardhat
- cmd: npx hardhat node
  cmd_settings:
    fork: mainnet
    port: 8545
  host: http://127.0.0.1
  id: mainnet-fork
  name: Hardhat (Mainnet Fork)
  timeout: 120
- cmd: npx hardhat node
  cmd_settings:
    fork: kovan
    port: 8545
  host: http://127.0.0.1
  id: kovan-fork
  name: Hardhat (Kovan Fork)
  timeout: 120
- cmd: npx hardhat node
  cmd_settings:
    fork: goerli
    port: 8545
  host: http://127.0.0.1
  id: goerli-fork
  name: goerli-fork
  timeout: 120
live:
- name: Ethereum
  networks:
  - chainid: 3
    explorer: https://api-ropsten.etherscan.io/api
    id: ropsten
    provider: infura
    name: Ropsten (Infura)
  - chainid: 4
    explorer: https://api-rinkeby.etherscan.io/api
    id: rinkeby
    provider: infura
    name: Rinkeby (Infura)
  - chainid: 42
    explorer: https://api-kovan.etherscan.io/api
    id: kovan
    provider: infura
    name: Kovan (Infura)
  - chainid: 1
    explorer: https://api.etherscan.io/api
    id: mainnet
    name: Mainnet (Alchemy)
    provider: alchemy
  - chainid: 421611
    explorer: https://testnet.arbiscan.io/
    provider: alchemy
    id: arbitrum-testnet
    name: Arbitrum Testnet
  - chainid: 5
    explorer: https://api-goerli.etherscan.io/api
    provider: alchemy
    id: goerli
    name: goerli
